-- =====================================================
-- Function: Get Screener Data at Specific Date
-- =====================================================
-- Wide screener row: performance (all horizons), category rank %,
-- fees (annual + prospectus), absolute & relative risk, Morningstar
-- ratings metrics, fund-level flows, AUM.
--
-- Adding/removing RETURN TABLE columns changes the row type; drop first.
-- =====================================================

DROP FUNCTION IF EXISTS ms.fn_get_screener_at_date(TEXT, TEXT, DATE);

CREATE OR REPLACE FUNCTION ms.fn_get_screener_at_date(
    p_category TEXT DEFAULT NULL,
    p_type     TEXT DEFAULT NULL,
    p_asof_date DATE DEFAULT NULL
)
RETURNS TABLE (
    _id            TEXT,
    fundname       TEXT,
    ticker         TEXT,
    categoryname   TEXT,
    securitytype   TEXT,
    return1mth     NUMERIC,
    return2mth     NUMERIC,
    return3mth     NUMERIC,
    return6mth     NUMERIC,
    return9mth     NUMERIC,
    return1yr      NUMERIC,
    return2yr      NUMERIC,
    return3yr      NUMERIC,
    return4yr      NUMERIC,
    return5yr      NUMERIC,
    return6yr      NUMERIC,
    return7yr      NUMERIC,
    return8yr      NUMERIC,
    return9yr      NUMERIC,
    return10yr     NUMERIC,
    return15yr     NUMERIC,
    return20yr     NUMERIC,
    returnytd      NUMERIC,
    returnsinceinception NUMERIC,
    cumulativereturn2yr NUMERIC,
    cumulativereturn3yr NUMERIC,
    cumulativereturn4yr NUMERIC,
    cumulativereturn5yr NUMERIC,
    cumulativereturn6yr NUMERIC,
    cumulativereturn7yr NUMERIC,
    cumulativereturn8yr NUMERIC,
    cumulativereturn9yr NUMERIC,
    cumulativereturn10yr NUMERIC,
    cumulativereturn15yr NUMERIC,
    cumulativereturn20yr NUMERIC,
    cumulativereturnsinceinception NUMERIC,
    rankytd        NUMERIC,
    rank1mth       NUMERIC,
    rank2mth       NUMERIC,
    rank3mth       NUMERIC,
    rank6mth       NUMERIC,
    rank9mth       NUMERIC,
    rank1yr        NUMERIC,
    rank2yr        NUMERIC,
    rank3yr        NUMERIC,
    rank4yr        NUMERIC,
    rank5yr        NUMERIC,
    rank6yr        NUMERIC,
    rank7yr        NUMERIC,
    rank8yr        NUMERIC,
    rank9yr        NUMERIC,
    rank10yr       NUMERIC,
    rank15yr       NUMERIC,
    rank20yr       NUMERIC,
    mer            NUMERIC,
    interimnetexpenseratio NUMERIC,
    tradingexpenseratio NUMERIC,
    prospectusnetexpenseratio NUMERIC,
    prospectusgrossexpenseratio NUMERIC,
    prospectusmgmtfee NUMERIC,
    stddev1yr      NUMERIC,
    stddev3yr      NUMERIC,
    stddev5yr      NUMERIC,
    stddev10yr     NUMERIC,
    stddev15yr     NUMERIC,
    stddev20yr     NUMERIC,
    maxdrawdown1yr NUMERIC,
    maxdrawdown3yr NUMERIC,
    maxdrawdown5yr NUMERIC,
    maxdrawdown10yr NUMERIC,
    skewness1yr    NUMERIC,
    skewness3yr    NUMERIC,
    skewness5yr    NUMERIC,
    kurtosis1yr    NUMERIC,
    kurtosis3yr    NUMERIC,
    kurtosis5yr    NUMERIC,
    sharperatio1yr NUMERIC,
    sharperatio3yr NUMERIC,
    sharperatio5yr NUMERIC,
    sharperatio10yr NUMERIC,
    alpha1yr       NUMERIC,
    alpha3yr       NUMERIC,
    alpha5yr       NUMERIC,
    alpha10yr      NUMERIC,
    alpha15yr      NUMERIC,
    alpha20yr      NUMERIC,
    beta1yr        NUMERIC,
    beta3yr        NUMERIC,
    beta5yr        NUMERIC,
    beta10yr       NUMERIC,
    beta15yr       NUMERIC,
    beta20yr       NUMERIC,
    rsquared1yr    NUMERIC,
    rsquared3yr    NUMERIC,
    rsquared5yr    NUMERIC,
    rsquared10yr   NUMERIC,
    captureratioupside1yr NUMERIC,
    captureratioupside3yr NUMERIC,
    captureratioupside5yr NUMERIC,
    captureratioupside10yr NUMERIC,
    captureratiodownside1yr NUMERIC,
    captureratiodownside3yr NUMERIC,
    captureratiodownside5yr NUMERIC,
    captureratiodownside10yr NUMERIC,
    informationratio1yr NUMERIC,
    informationratio3yr NUMERIC,
    informationratio5yr NUMERIC,
    informationratio10yr NUMERIC,
    rating3year    NUMERIC,
    rating5year    NUMERIC,
    rating10year   NUMERIC,
    ratingoverall  NUMERIC,
    riskadjustedreturn3yr NUMERIC,
    riskadjustedreturn5yr NUMERIC,
    riskadjustedreturn10yr NUMERIC,
    riskadjustedreturnoverall NUMERIC,
    performancescore3yr NUMERIC,
    performancescore5yr NUMERIC,
    performancescore10yr NUMERIC,
    performancescoreoverall NUMERIC,
    riskscore3yr   NUMERIC,
    riskscore5yr   NUMERIC,
    riskscore10yr  NUMERIC,
    riskscoreoverall NUMERIC,
    numberoffunds3year NUMERIC,
    numberoffunds5year NUMERIC,
    numberoffunds10year NUMERIC,
    numberoffundsoverall NUMERIC,
    perfcatrank3year NUMERIC,
    perfcatrank5year NUMERIC,
    perfcatrank10year NUMERIC,
    riskcatrank3year NUMERIC,
    riskcatrank5year NUMERIC,
    riskcatrank10year NUMERIC,
    ratingcatrank3year NUMERIC,
    ratingcatrank5year NUMERIC,
    ratingcatrank10year NUMERIC,
    estfundlevelnetflow1momoend NUMERIC,
    estfundlevelnetflow3momoend NUMERIC,
    estfundlevelnetflow6momoend NUMERIC,
    estfundlevelnetflow1yrmoend NUMERIC,
    estfundlevelnetflow3yrmoend NUMERIC,
    estfundlevelnetflow5yrmoend NUMERIC,
    estfundlevelnetflow10yrmoend NUMERIC,
    estfundlevelnetflow15yrmoend NUMERIC,
    estfundlevelnetflowytdmoend NUMERIC,
    fundnetassets  NUMERIC
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_asof_date DATE;
BEGIN
    IF p_asof_date IS NOT NULL THEN
        v_asof_date := p_asof_date;
    ELSE
        SELECT MAX(monthenddate::DATE) INTO v_asof_date
        FROM ms.month_end_trailing_total_returns_ca_openend
        WHERE monthenddate IS NOT NULL;
    END IF;

    IF p_asof_date IS NULL THEN
        RETURN QUERY
        SELECT
            bf._id,
            bf.fundname,
            bf.ticker,
            bf.categoryname,
            bf.securitytype,
            perf.return1mth::NUMERIC,
            perf.return2mth::NUMERIC,
            perf.return3mth::NUMERIC,
            perf.return6mth::NUMERIC,
            perf.return9mth::NUMERIC,
            perf.return1yr::NUMERIC,
            perf.return2yr::NUMERIC,
            perf.return3yr::NUMERIC,
            perf.return4yr::NUMERIC,
            perf.return5yr::NUMERIC,
            perf.return6yr::NUMERIC,
            perf.return7yr::NUMERIC,
            perf.return8yr::NUMERIC,
            perf.return9yr::NUMERIC,
            perf.return10yr::NUMERIC,
            perf.return15yr::NUMERIC,
            perf.return20yr::NUMERIC,
            perf.returnytd::NUMERIC,
            perf.returnsinceinception::NUMERIC,
            perf.cumulativereturn2yr::NUMERIC,
            perf.cumulativereturn3yr::NUMERIC,
            perf.cumulativereturn4yr::NUMERIC,
            perf.cumulativereturn5yr::NUMERIC,
            perf.cumulativereturn6yr::NUMERIC,
            perf.cumulativereturn7yr::NUMERIC,
            perf.cumulativereturn8yr::NUMERIC,
            perf.cumulativereturn9yr::NUMERIC,
            perf.cumulativereturn10yr::NUMERIC,
            perf.cumulativereturn15yr::NUMERIC,
            perf.cumulativereturn20yr::NUMERIC,
            perf.cumulativereturnsinceinception::NUMERIC,
            rk.rankytd::NUMERIC,
            rk.rank1mth::NUMERIC,
            rk.rank2mth::NUMERIC,
            rk.rank3mth::NUMERIC,
            rk.rank6mth::NUMERIC,
            rk.rank9mth::NUMERIC,
            rk.rank1yr::NUMERIC,
            rk.rank2yr::NUMERIC,
            rk.rank3yr::NUMERIC,
            rk.rank4yr::NUMERIC,
            rk.rank5yr::NUMERIC,
            rk.rank6yr::NUMERIC,
            rk.rank7yr::NUMERIC,
            rk.rank8yr::NUMERIC,
            rk.rank9yr::NUMERIC,
            rk.rank10yr::NUMERIC,
            rk.rank15yr::NUMERIC,
            rk.rank20yr::NUMERIC,
            fees.mer::NUMERIC,
            fees.interimnetexpenseratio::NUMERIC,
            fees.tradingexpenseratio::NUMERIC,
            pfees.netexpenseratio::NUMERIC,
            pfees.grossexpenseratio::NUMERIC,
            pfees.actualmanagementfee::NUMERIC,
            rabs.stddev1yr::NUMERIC,
            rabs.stddev3yr::NUMERIC,
            rabs.stddev5yr::NUMERIC,
            rabs.stddev10yr::NUMERIC,
            rabs.stddev15yr::NUMERIC,
            rabs.stddev20yr::NUMERIC,
            rabs.maxdrawdown1yr::NUMERIC,
            rabs.maxdrawdown3yr::NUMERIC,
            rabs.maxdrawdown5yr::NUMERIC,
            rabs.maxdrawdown10yr::NUMERIC,
            rabs.skewness1yr::NUMERIC,
            rabs.skewness3yr::NUMERIC,
            rabs.skewness5yr::NUMERIC,
            rabs.kurtosis1yr::NUMERIC,
            rabs.kurtosis3yr::NUMERIC,
            rabs.kurtosis5yr::NUMERIC,
            rabs.sharperatio1yr::NUMERIC,
            rabs.sharperatio3yr::NUMERIC,
            rabs.sharperatio5yr::NUMERIC,
            rabs.sharperatio10yr::NUMERIC,
            rrel.alpha1yr::NUMERIC,
            rrel.alpha3yr::NUMERIC,
            rrel.alpha5yr::NUMERIC,
            rrel.alpha10yr::NUMERIC,
            rrel.alpha15yr::NUMERIC,
            rrel.alpha20yr::NUMERIC,
            rrel.beta1yr::NUMERIC,
            rrel.beta3yr::NUMERIC,
            rrel.beta5yr::NUMERIC,
            rrel.beta10yr::NUMERIC,
            rrel.beta15yr::NUMERIC,
            rrel.beta20yr::NUMERIC,
            rrel.rsquared1yr::NUMERIC,
            rrel.rsquared3yr::NUMERIC,
            rrel.rsquared5yr::NUMERIC,
            rrel.rsquared10yr::NUMERIC,
            rrel.captureratioupside1yr::NUMERIC,
            rrel.captureratioupside3yr::NUMERIC,
            rrel.captureratioupside5yr::NUMERIC,
            rrel.captureratioupside10yr::NUMERIC,
            rrel.captureratiodownside1yr::NUMERIC,
            rrel.captureratiodownside3yr::NUMERIC,
            rrel.captureratiodownside5yr::NUMERIC,
            rrel.captureratiodownside10yr::NUMERIC,
            rrel.informationratio1yr::NUMERIC,
            rrel.informationratio3yr::NUMERIC,
            rrel.informationratio5yr::NUMERIC,
            rrel.informationratio10yr::NUMERIC,
            rat.rating3year::NUMERIC,
            rat.rating5year::NUMERIC,
            rat.rating10year::NUMERIC,
            rat.ratingoverall::NUMERIC,
            rat.riskadjustedreturn3yr::NUMERIC,
            rat.riskadjustedreturn5yr::NUMERIC,
            rat.riskadjustedreturn10yr::NUMERIC,
            rat.riskadjustedreturnoverall::NUMERIC,
            rat.performancescore3yr::NUMERIC,
            rat.performancescore5yr::NUMERIC,
            rat.performancescore10yr::NUMERIC,
            rat.performancescoreoverall::NUMERIC,
            rat.riskscore3yr::NUMERIC,
            rat.riskscore5yr::NUMERIC,
            rat.riskscore10yr::NUMERIC,
            rat.riskscoreoverall::NUMERIC,
            rat.numberoffunds3year::NUMERIC,
            rat.numberoffunds5year::NUMERIC,
            rat.numberoffunds10year::NUMERIC,
            rat.numberoffundsoverall::NUMERIC,
            rat.perfcatrank3year::NUMERIC,
            rat.perfcatrank5year::NUMERIC,
            rat.perfcatrank10year::NUMERIC,
            rat.riskcatrank3year::NUMERIC,
            rat.riskcatrank5year::NUMERIC,
            rat.riskcatrank10year::NUMERIC,
            rat.ratingcatrank3year::NUMERIC,
            rat.ratingcatrank5year::NUMERIC,
            rat.ratingcatrank10year::NUMERIC,
            fl.estfundlevelnetflow1momoend::NUMERIC,
            fl.estfundlevelnetflow3momoend::NUMERIC,
            fl.estfundlevelnetflow6momoend::NUMERIC,
            fl.estfundlevelnetflow1yrmoend::NUMERIC,
            fl.estfundlevelnetflow3yrmoend::NUMERIC,
            fl.estfundlevelnetflow5yrmoend::NUMERIC,
            fl.estfundlevelnetflow10yrmoend::NUMERIC,
            fl.estfundlevelnetflow15yrmoend::NUMERIC,
            fl.estfundlevelnetflowytdmoend::NUMERIC,
            assets.fundnetassets::NUMERIC
        FROM ms.mv_fund_share_class_basic_info_ca_openend_latest bf
        LEFT JOIN ms.month_end_trailing_total_returns_ca_openend perf
            ON perf._id = bf._id AND perf.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.month_end_trailing_total_return_percentile_and_absolute_ranks_c rk
            ON rk._id = bf._id AND rk.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.annual_report_fees_ca_openend fees
            ON fees._id = bf._id AND fees.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.prospectus_fees_ca_openend pfees
            ON pfees._id = bf._id AND pfees.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.risk_measure_ca_openend rabs
            ON rabs._id = bf._id AND rabs.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.relative_risk_measure_prospectus_ca_openend rrel
            ON rrel._id = bf._id AND rrel.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.morningstar_rating_ca_openend rat
            ON rat._id = bf._id AND rat.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.fund_flow_details_ca_openend fl
            ON fl._id = bf._id AND fl.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.fund_level_net_assets_ca_openend assets
            ON assets._id = bf._id AND assets.monthenddate = v_asof_date::TEXT
        WHERE (p_category IS NULL OR bf.categoryname = p_category)
          AND (p_type IS NULL OR bf.securitytype = p_type);
    ELSE
        RETURN QUERY
        SELECT
            bf._id,
            bf.fundname,
            bf.ticker,
            bf.categoryname,
            CASE bf.securitytype
                WHEN 'FO' THEN 'Mutual Fund'
                WHEN 'FE' THEN 'ETF'
                ELSE bf.securitytype
            END,
            perf.return1mth::NUMERIC,
            perf.return2mth::NUMERIC,
            perf.return3mth::NUMERIC,
            perf.return6mth::NUMERIC,
            perf.return9mth::NUMERIC,
            perf.return1yr::NUMERIC,
            perf.return2yr::NUMERIC,
            perf.return3yr::NUMERIC,
            perf.return4yr::NUMERIC,
            perf.return5yr::NUMERIC,
            perf.return6yr::NUMERIC,
            perf.return7yr::NUMERIC,
            perf.return8yr::NUMERIC,
            perf.return9yr::NUMERIC,
            perf.return10yr::NUMERIC,
            perf.return15yr::NUMERIC,
            perf.return20yr::NUMERIC,
            perf.returnytd::NUMERIC,
            perf.returnsinceinception::NUMERIC,
            perf.cumulativereturn2yr::NUMERIC,
            perf.cumulativereturn3yr::NUMERIC,
            perf.cumulativereturn4yr::NUMERIC,
            perf.cumulativereturn5yr::NUMERIC,
            perf.cumulativereturn6yr::NUMERIC,
            perf.cumulativereturn7yr::NUMERIC,
            perf.cumulativereturn8yr::NUMERIC,
            perf.cumulativereturn9yr::NUMERIC,
            perf.cumulativereturn10yr::NUMERIC,
            perf.cumulativereturn15yr::NUMERIC,
            perf.cumulativereturn20yr::NUMERIC,
            perf.cumulativereturnsinceinception::NUMERIC,
            rk.rankytd::NUMERIC,
            rk.rank1mth::NUMERIC,
            rk.rank2mth::NUMERIC,
            rk.rank3mth::NUMERIC,
            rk.rank6mth::NUMERIC,
            rk.rank9mth::NUMERIC,
            rk.rank1yr::NUMERIC,
            rk.rank2yr::NUMERIC,
            rk.rank3yr::NUMERIC,
            rk.rank4yr::NUMERIC,
            rk.rank5yr::NUMERIC,
            rk.rank6yr::NUMERIC,
            rk.rank7yr::NUMERIC,
            rk.rank8yr::NUMERIC,
            rk.rank9yr::NUMERIC,
            rk.rank10yr::NUMERIC,
            rk.rank15yr::NUMERIC,
            rk.rank20yr::NUMERIC,
            fees.mer::NUMERIC,
            fees.interimnetexpenseratio::NUMERIC,
            fees.tradingexpenseratio::NUMERIC,
            pfees.netexpenseratio::NUMERIC,
            pfees.grossexpenseratio::NUMERIC,
            pfees.actualmanagementfee::NUMERIC,
            rabs.stddev1yr::NUMERIC,
            rabs.stddev3yr::NUMERIC,
            rabs.stddev5yr::NUMERIC,
            rabs.stddev10yr::NUMERIC,
            rabs.stddev15yr::NUMERIC,
            rabs.stddev20yr::NUMERIC,
            rabs.maxdrawdown1yr::NUMERIC,
            rabs.maxdrawdown3yr::NUMERIC,
            rabs.maxdrawdown5yr::NUMERIC,
            rabs.maxdrawdown10yr::NUMERIC,
            rabs.skewness1yr::NUMERIC,
            rabs.skewness3yr::NUMERIC,
            rabs.skewness5yr::NUMERIC,
            rabs.kurtosis1yr::NUMERIC,
            rabs.kurtosis3yr::NUMERIC,
            rabs.kurtosis5yr::NUMERIC,
            rabs.sharperatio1yr::NUMERIC,
            rabs.sharperatio3yr::NUMERIC,
            rabs.sharperatio5yr::NUMERIC,
            rabs.sharperatio10yr::NUMERIC,
            rrel.alpha1yr::NUMERIC,
            rrel.alpha3yr::NUMERIC,
            rrel.alpha5yr::NUMERIC,
            rrel.alpha10yr::NUMERIC,
            rrel.alpha15yr::NUMERIC,
            rrel.alpha20yr::NUMERIC,
            rrel.beta1yr::NUMERIC,
            rrel.beta3yr::NUMERIC,
            rrel.beta5yr::NUMERIC,
            rrel.beta10yr::NUMERIC,
            rrel.beta15yr::NUMERIC,
            rrel.beta20yr::NUMERIC,
            rrel.rsquared1yr::NUMERIC,
            rrel.rsquared3yr::NUMERIC,
            rrel.rsquared5yr::NUMERIC,
            rrel.rsquared10yr::NUMERIC,
            rrel.captureratioupside1yr::NUMERIC,
            rrel.captureratioupside3yr::NUMERIC,
            rrel.captureratioupside5yr::NUMERIC,
            rrel.captureratioupside10yr::NUMERIC,
            rrel.captureratiodownside1yr::NUMERIC,
            rrel.captureratiodownside3yr::NUMERIC,
            rrel.captureratiodownside5yr::NUMERIC,
            rrel.captureratiodownside10yr::NUMERIC,
            rrel.informationratio1yr::NUMERIC,
            rrel.informationratio3yr::NUMERIC,
            rrel.informationratio5yr::NUMERIC,
            rrel.informationratio10yr::NUMERIC,
            rat.rating3year::NUMERIC,
            rat.rating5year::NUMERIC,
            rat.rating10year::NUMERIC,
            rat.ratingoverall::NUMERIC,
            rat.riskadjustedreturn3yr::NUMERIC,
            rat.riskadjustedreturn5yr::NUMERIC,
            rat.riskadjustedreturn10yr::NUMERIC,
            rat.riskadjustedreturnoverall::NUMERIC,
            rat.performancescore3yr::NUMERIC,
            rat.performancescore5yr::NUMERIC,
            rat.performancescore10yr::NUMERIC,
            rat.performancescoreoverall::NUMERIC,
            rat.riskscore3yr::NUMERIC,
            rat.riskscore5yr::NUMERIC,
            rat.riskscore10yr::NUMERIC,
            rat.riskscoreoverall::NUMERIC,
            rat.numberoffunds3year::NUMERIC,
            rat.numberoffunds5year::NUMERIC,
            rat.numberoffunds10year::NUMERIC,
            rat.numberoffundsoverall::NUMERIC,
            rat.perfcatrank3year::NUMERIC,
            rat.perfcatrank5year::NUMERIC,
            rat.perfcatrank10year::NUMERIC,
            rat.riskcatrank3year::NUMERIC,
            rat.riskcatrank5year::NUMERIC,
            rat.riskcatrank10year::NUMERIC,
            rat.ratingcatrank3year::NUMERIC,
            rat.ratingcatrank5year::NUMERIC,
            rat.ratingcatrank10year::NUMERIC,
            fl.estfundlevelnetflow1momoend::NUMERIC,
            fl.estfundlevelnetflow3momoend::NUMERIC,
            fl.estfundlevelnetflow6momoend::NUMERIC,
            fl.estfundlevelnetflow1yrmoend::NUMERIC,
            fl.estfundlevelnetflow3yrmoend::NUMERIC,
            fl.estfundlevelnetflow5yrmoend::NUMERIC,
            fl.estfundlevelnetflow10yrmoend::NUMERIC,
            fl.estfundlevelnetflow15yrmoend::NUMERIC,
            fl.estfundlevelnetflowytdmoend::NUMERIC,
            assets.fundnetassets::NUMERIC
        FROM ms.fund_share_class_basic_info_ca_openend bf
        LEFT JOIN ms.month_end_trailing_total_returns_ca_openend perf
            ON perf._id = bf._id AND perf.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.month_end_trailing_total_return_percentile_and_absolute_ranks_c rk
            ON rk._id = bf._id AND rk.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.annual_report_fees_ca_openend fees
            ON fees._id = bf._id AND fees.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.prospectus_fees_ca_openend pfees
            ON pfees._id = bf._id AND pfees.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.risk_measure_ca_openend rabs
            ON rabs._id = bf._id AND rabs.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.relative_risk_measure_prospectus_ca_openend rrel
            ON rrel._id = bf._id AND rrel.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.morningstar_rating_ca_openend rat
            ON rat._id = bf._id AND rat.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.fund_flow_details_ca_openend fl
            ON fl._id = bf._id AND fl.monthenddate = v_asof_date::TEXT
        LEFT JOIN ms.fund_level_net_assets_ca_openend assets
            ON assets._id = bf._id AND assets.monthenddate = v_asof_date::TEXT
        WHERE bf.monthenddate = v_asof_date::TEXT
          AND (p_category IS NULL OR bf.categoryname = p_category)
          AND (p_type IS NULL OR
               CASE bf.securitytype
                   WHEN 'FO' THEN 'Mutual Fund'
                   WHEN 'FE' THEN 'ETF'
                   ELSE bf.securitytype
               END = p_type);
    END IF;
END;
$$;
