/**
 * Column names exposed by ms.fn_get_screener_at_date (numeric / sortable).
 * Keep in sync with server/db/sql/functions/09_screener_at_date.sql and
 * client/src/config/screenerMetrics.js (valuePath / apiField).
 */

const RANK_PERCENTILE_SORT_KEYS = [
  'rankytd',
  'rank1mth',
  'rank2mth',
  'rank3mth',
  'rank6mth',
  'rank9mth',
  'rank1yr',
  'rank2yr',
  'rank3yr',
  'rank4yr',
  'rank5yr',
  'rank6yr',
  'rank7yr',
  'rank8yr',
  'rank9yr',
  'rank10yr',
  'rank15yr',
  'rank20yr',
];

const PERF_TRAILING_SORT_KEYS = [
  'return1mth',
  'return2mth',
  'return3mth',
  'return6mth',
  'return9mth',
  'return1yr',
  'return2yr',
  'return3yr',
  'return4yr',
  'return5yr',
  'return6yr',
  'return7yr',
  'return8yr',
  'return9yr',
  'return10yr',
  'return15yr',
  'return20yr',
  'returnytd',
  'returnsinceinception',
];

const PERF_CUMULATIVE_SORT_KEYS = [
  'cumulativereturn2yr',
  'cumulativereturn3yr',
  'cumulativereturn4yr',
  'cumulativereturn5yr',
  'cumulativereturn6yr',
  'cumulativereturn7yr',
  'cumulativereturn8yr',
  'cumulativereturn9yr',
  'cumulativereturn10yr',
  'cumulativereturn15yr',
  'cumulativereturn20yr',
  'cumulativereturnsinceinception',
];

const FEE_SORT_KEYS = [
  'mer',
  'interimnetexpenseratio',
  'tradingexpenseratio',
  'prospectusnetexpenseratio',
  'prospectusgrossexpenseratio',
  'prospectusmgmtfee',
];

const RISK_ABS_SORT_KEYS = [
  'stddev1yr',
  'stddev3yr',
  'stddev5yr',
  'stddev10yr',
  'stddev15yr',
  'stddev20yr',
  'maxdrawdown1yr',
  'maxdrawdown3yr',
  'maxdrawdown5yr',
  'maxdrawdown10yr',
  'skewness1yr',
  'skewness3yr',
  'skewness5yr',
  'kurtosis1yr',
  'kurtosis3yr',
  'kurtosis5yr',
  'sharperatio1yr',
  'sharperatio3yr',
  'sharperatio5yr',
  'sharperatio10yr',
];

const RISK_REL_SORT_KEYS = [
  'alpha1yr',
  'alpha3yr',
  'alpha5yr',
  'alpha10yr',
  'alpha15yr',
  'alpha20yr',
  'beta1yr',
  'beta3yr',
  'beta5yr',
  'beta10yr',
  'beta15yr',
  'beta20yr',
  'rsquared1yr',
  'rsquared3yr',
  'rsquared5yr',
  'rsquared10yr',
  'captureratioupside1yr',
  'captureratioupside3yr',
  'captureratioupside5yr',
  'captureratioupside10yr',
  'captureratiodownside1yr',
  'captureratiodownside3yr',
  'captureratiodownside5yr',
  'captureratiodownside10yr',
  'informationratio1yr',
  'informationratio3yr',
  'informationratio5yr',
  'informationratio10yr',
];

const RATING_SORT_KEYS = [
  'rating3year',
  'rating5year',
  'rating10year',
  'ratingoverall',
  'riskadjustedreturn3yr',
  'riskadjustedreturn5yr',
  'riskadjustedreturn10yr',
  'riskadjustedreturnoverall',
  'performancescore3yr',
  'performancescore5yr',
  'performancescore10yr',
  'performancescoreoverall',
  'riskscore3yr',
  'riskscore5yr',
  'riskscore10yr',
  'riskscoreoverall',
  'numberoffunds3year',
  'numberoffunds5year',
  'numberoffunds10year',
  'numberoffundsoverall',
  'perfcatrank3year',
  'perfcatrank5year',
  'perfcatrank10year',
  'riskcatrank3year',
  'riskcatrank5year',
  'riskcatrank10year',
  'ratingcatrank3year',
  'ratingcatrank5year',
  'ratingcatrank10year',
];

const FLOW_SORT_KEYS = [
  'estfundlevelnetflow1momoend',
  'estfundlevelnetflow3momoend',
  'estfundlevelnetflow6momoend',
  'estfundlevelnetflow1yrmoend',
  'estfundlevelnetflow3yrmoend',
  'estfundlevelnetflow5yrmoend',
  'estfundlevelnetflow10yrmoend',
  'estfundlevelnetflow15yrmoend',
  'estfundlevelnetflowytdmoend',
];

const ALL_SCREENER_SORT_KEYS = [
  ...PERF_TRAILING_SORT_KEYS,
  ...PERF_CUMULATIVE_SORT_KEYS,
  ...RANK_PERCENTILE_SORT_KEYS,
  ...FEE_SORT_KEYS,
  ...RISK_ABS_SORT_KEYS,
  ...RISK_REL_SORT_KEYS,
  ...RATING_SORT_KEYS,
  ...FLOW_SORT_KEYS,
  'fundnetassets',
];

module.exports = {
  RANK_PERCENTILE_SORT_KEYS,
  PERF_TRAILING_SORT_KEYS,
  PERF_CUMULATIVE_SORT_KEYS,
  FEE_SORT_KEYS,
  RISK_ABS_SORT_KEYS,
  RISK_REL_SORT_KEYS,
  RATING_SORT_KEYS,
  FLOW_SORT_KEYS,
  ALL_SCREENER_SORT_KEYS,
};
